---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prefect-agent
  name: prefect-agent
  namespace: ${BAKERY_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-agent
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
        - args: ["prefect", "agent", "kubernetes", "start"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: google-credentials
              mountPath:  /opt
          env:
            - name: PREFECT__CLOUD__AGENT__AUTH_TOKEN
              value: ${PREFECT__CLOUD__AGENT__AUTH_TOKEN}
            - name: PREFECT__CLOUD__API
              value: https://api.prefect.io
            - name: NAMESPACE
              value: ${BAKERY_NAMESPACE}
            - name: PREFECT__CLOUD__AGENT__LABELS
              value: '${PREFECT__CLOUD__AGENT__LABELS}'
            - name: SERVICE_ACCOUNT_NAME
              value: 'default'
            - name: PREFECT__BACKEND
              value: cloud
            - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
              value: http://:8080
            - name: DELETE_FINISHED_JOBS
              value: 'False'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/opt/googlecreds.json"
          image: ${BAKERY_IMAGE}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 40
          name: agent
      volumes:
        - name: google-credentials
          secret:
            secretName: google-credentials
